/**
 * auth action types
 */

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const RESET_CODE_REQUEST = 'RESET_CODE_REQUEST';
export const RESET_CODE_SUCCESS = 'RESET_CODE_SUCCESS';
export const RESET_CODE_FAILURE = 'RESET_CODE_FAILURE';

/**
 * admin request data
 */
export const ADMIN_REQUEST = 'ADMIN_REQUEST';
export const ADMIN_FAILURE = 'ADMIN_FAILURE';

export const ADMIN_USER_SUCCESS = 'ADMIN_USER_SUCCESS';
export const ADMIN_LEGACY_SUCCESS = 'ADMIN_LEGACY_SUCCESS';
export const ADMIN_BURIAL_SUCCESS = 'ADMIN_BURIAL_SUCCESS';
export const ADMIN_CHARITY_SUCCESS = 'ADMIN_CHARITY_SUCCESS';
export const ADMIN_DONATION_SUCCESS = 'ADMIN_DONATION_SUCCESS';

/**
 * get user profile data
 */

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

/**
 * get memorial request
 */
export const GET_MEMORIAL_REQUEST = 'GET_MEMORIAL_REQUEST'
export const GET_MEMORIAL_SUCCESS = 'GET_MEMORIAL_SUCCESS'
export const GET_MEMORIAL_FAILURE = 'GET_MEMORIAL_FAILURE'

/**
 * get count request
 */

export const COUNT_REQUEST = 'COUNT_REQUEST';
export const COUNT_SUCCESS = 'COUNT_SUCCESS';
export const COUNT_FAILURE = 'COUNT_FAILURE';

/**
 * admin profile request
 */

export const ADMIN_PROFILE_REQUEST = 'ADMIN_PROFILE_REQUEST';
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS';
export const ADMIN_PROFILE_FAILURE = 'ADMIN_PROFILE_FAILURE';

/**
 * donations requests
 */

export const GET_DONATION_REQUEST = 'GET_DONATION_REQUEST';
export const GET_DONATION_SUCCESS = 'GET_DONATION_SUCCESS';
export const GET_DONATION_FAILURE = 'GET_DONATION_FAILURE';

/**
 * send donation request
 */

export const SEND_DONATION_REQUEST = 'SEND_DONATION_REQUEST';
export const SEND_DONATION_SUCCESS = 'SEND_DONATION_SUCCESS';
export const SEND_DONATION_FAILURE = 'SEND_DONATION_FAILURE';
